SERVER = ''
USERNAME = ''
PASSWORD = ''

def args
  []
end

def random_word(length, capitalize = false)
  capitalize ? (0...length).map { ('a'..'z').to_a[rand(26)] }.join.capitalize : (0...length).map { ('a'..'z').to_a[rand(26)] }.join
end

def random_email
  random_word(7) + '@sharklasers.com'
end

#region OPTIONS
#region People
SEARCH_USER_NAME = 'Allison'
USER_FILTER = { activationStatus: 1 }
USER_ID = 'efcb452b-2be3-4311-b539-fabad4d42e95'#'e83cceef-2cbf-4cdf-9a4c-fea4e810705b'
USERNAME_FOR_OPERATIONS = 'kcwijpgg'
USER_STATUS = 'Active'
SEARCH_QUERY = random_word(7, true)
USER_EMAIL = random_email
IS_VISITOR = false
NEW_USER_FIRSTNAME = random_word(7, true)
NEW_USER_LASTNAME = random_word(7, true)
USER_CONTACTS = [
                { type: 'skype', value: 'mondovoshka' },
                { type: 'email', value: 'mondovoshka@mail.ru' }
                ]
FEW_USER_IDS = %w(37f5ce64-9db1-4df9-8b93-436e39721b4d 6d5c7d2f-b81e-4afb-b5d6-cd6ef2426e35)
USERS_TO_DELETE = ['864663e3-6135-4252-a11c-e507f96e59a9']
USER_TYPE = 'User'
PATH_TO_IMAGE = 'http://ic.pics.livejournal.com/scryp/14761862/5478/5478_original.jpg'
#endregion

#region Group
GROUP_ID = '06a9bf1b-3354-4347-805c-934265b62773'
GROUP_NAME = random_word(7)
GROUP_ID_FOR_OPERATIONS = 'd868c0fb-d669-495f-aa00-1279395285ea'
GROUP_UPDATE_OPTIONS = { groupManager: USER_ID, groupName: GROUP_NAME, members: FEW_USER_IDS }
GROUP_ID_TO_DELETE = '97b92796-79b1-4688-869e-1d09487d91d8'
#endregion

#regions Settings
SETTINGS_ENTITY_IDS = ['ea942538-e68e-4907-9394-035336ee0ba8', '28b10049-dd20-4f54-b986-873bc14ccfc7']
SETTINGS_TEST_USER = '27cd9da5-4f97-4335-ac45-55dd05d96d89'
SETTINGS_TALK_MODULE_ID = 'bf88953e-3c43-4850-a3fb-b1e43ad53a3e'
SETTINGS_VERSION = 2
SETTINGS_FOR_TALK = { enabled: true }
#endregion

#region Files
FOLDER_COMMON_DOCS_ID = '225508'
FOLDER_TITLE = random_word(10)
FOLDER_FOR_OPERATIONS_ID = '168228'
FILE_FOR_OPERATIONS_ID = '3434235'
FILE_FOR_OPERATIONS_VERSION = 1
FILES_SHARE_TYPE = 'Read'
FILE_TO_UPLOAD = '/home/zagudaev-2/mods.txt'
FILE_MORE_THAN_5_MB = '/mnt/data_share/Files/PDF/AllPDF/600 Essential Words for the TOEIC Test.pdf'
FILE_SIZE_IN_BYTES = 107374182.4
FEW_FILES_IDS = [3482982, 3482961, 3482965]
NEW_FILE_NAME = random_word(8)
NEW_FILE_CONTENT = random_word(40)
THIRD_PARTY_SERVICE = 'Box.com'
THIRD_PARTY_LOGIN = 'teamlab.ruby@gmail.com'
THIRD_PARTY_PASSWORD = '123456'
THIRD_PARTY_LOGIN_DATA = {login: THIRD_PARTY_LOGIN, password: THIRD_PARTY_PASSWORD}
THIRD_PARTY_FOLDER_ID = '1042248535'
IGNORE_COINCIDENCE_FILES = true
DATA_TO_IMPORT = []
FILE_TO_DELETE_ID = '3482889'
FOLDER_TO_DELETE_ID = '1555056'
ACCESS_TYPE = 1
NOTIFY_USER = true
NOTIFICATION_MESSAGE = random_word(10)
PROVIDER_ID = '12137'
#endregion

#region Projects
BASECAMP_URL = "https://basecamp.com/2452154"
BASECAMP_LOGIN = "qwegsdfs@qwe.ru"
BASECAMP_PSW = "123456"
IMPORT_CLOSED_PROJECTS = true
DISABLE_NOTIFICATONS = false
IMPORT_USERS_AS_COLLABORATORS = true
PROJECT_ID_FOR_OPERATIONS = '4322'
MESSAGE_ID = '3878'

TASK_ID = '12406'
RESPONSIBLE_ID = '187ecad1-eeb4-4173-a6c0-1c225ad72fb2'
RANDOM_TITLE = random_word(10, true)
PROJECT_DESCRIPTION = random_word(10, true)
ANOTHER_PROJECT_ID = 9735
MILESTONE_ID = 422849
SOME_DATE = '2015-03-23T14:27:14'
ANOTHER_DATE = '2015-06-10T06:30:00.0000000-07:00'
SIMPLE_DATE = '2011-10-1'
RANDOM_NOTE = random_word(12)
TIME_ID = 528238
#endregion

#region CRM
OPPORTUNITY_COLOR_NAME = 'red'
OPPORTUNITY_ID = '74156'
SUCCESS_PROBABILITY = 18
BID_TYPE = 'PerMonth'
PER_PERIOD_VALUE = 345
STAGE_ID = 110331
CONTACTS_IDS = [2971532, 2971531, 75613, 3065356, 3065355, 3065354, 3065353]
CONTACT_ID = 3065356
CONTACT_TYPE_ID = 235222
IS_PRIVATE = true
INVOICE_ID = 74
CATEGORY_ID = 1979
RANDOM_TAGS = [random_word(3), random_word(5)]
AUTOGENERATED = true
INVOICE_STATUS = 'Paid'
CONTACT_STATUS_ID = 1990
HISTORY_CATEGORY_ID = 241050
COMPANY_ID = 2971531
CONTACT_INFORMATION_ID = 452955
NEW_RANDOM_USERS_ARRAY = (1..rand(5)).collect { {firstName: random_word(rand(3..12), true), lastName: random_word(rand(3..12), true)} }
INFO_TYPE = 1#'Phone'
INFO_DATA = 54273553
INFO_CATEGORY = 'Work'
IMAGE_URL = 'http://thebooksmugglers.com/wp-content/uploads/2009/02/image002-200x300.jpg'#'http://www.soulscode.com/wp-content/uploads/2011/02/doll-200x300.jpg'
#endregion

#region Community
POST_ID = '797eb01e-b13f-49a4-9b4c-b74b40bad876'
BOOKMARK_ID = 288498
EVENT_ID = 63569
THREAD_ID = 4988
TOPIC_ID = 26560
COMMUNITY_CATEGORY_ID = 3779
THREAD_NAME = '1'
WIKI_PAGE_NAME = 'fsdf'
WIKI_FILE_NAME = 'rapuncel.jpg'
WIKI_PAGE_COMMENT_ID = '8a72589a-f9f0-44b7-aed4-1608335f1855'
#endregion

#region Calendar
CALENDAR_ID = 1395822265100
#endregion
#endregion