name: check
on: [push]
jobs:
  check-markdown:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/setup-node@v1
      - name: Install markdownlint
        run: npm install -g markdownlint-cli
      - name: Check all md files
        run: markdownlint *.md
  run-tests:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Set up Ruby 2.7
        uses: ruby/setup-ruby@v1
        with:
          ruby-version: 2.7
      - name: Build and test with Rake
        env:
          ONLYOFFICE_API_GEM_TEST_PORTAL: ${{ secrets.ONLYOFFICE_API_GEM_TEST_PORTAL }}
          ONLYOFFICE_API_GEM_TEST_USER: ${{ secrets.ONLYOFFICE_API_GEM_TEST_USER }}
          ONLYOFFICE_API_GEM_TEST_PASSWORD: ${{ secrets.ONLYOFFICE_API_GEM_TEST_PASSWORD }}
          ONLYOFFICE_API_GEM_MAIL_NAME: ${{ secrets.ONLYOFFICE_API_GEM_MAIL_NAME }}
          ONLYOFFICE_API_GEM_MAIL_PASS: ${{ secrets.ONLYOFFICE_API_GEM_MAIL_PASS }}
        run: |
          gem install bundler
          bundle install --jobs 4 --retry 3
          bundle exec rake
