name: Ruby
on: [push]
jobs:
  build:
    runs-on: ubuntu-latest
    concurrency:
      group: rspec_tests
      cancel-in-progress: false
    continue-on-error: ${{ matrix.allow-failures }}
    strategy:
      matrix:
        ruby: ['3.1', '3.2', '3.3', '3.4']
        allow-failures: [false]
        include:
          - ruby: head
            allow-failures: true
      max-parallel: 1
    steps:
      - uses: actions/checkout@v4
      - name: Set up Ruby ${{ matrix.ruby }}
        uses: ruby/setup-ruby@v1
        with:
          ruby-version: ${{ matrix.ruby }}
      - name: Install dependencies
        run: |
          gem install bundler
          bundle install --jobs 4 --retry 3
      - name: Run tests
        env:
          ONLYOFFICE_API_GEM_TEST_PORTAL: ${{ secrets.ONLYOFFICE_API_GEM_TEST_PORTAL }}
          ONLYOFFICE_API_GEM_TEST_USER: ${{ secrets.ONLYOFFICE_API_GEM_TEST_USER }}
          ONLYOFFICE_API_GEM_TEST_PASSWORD: ${{ secrets.ONLYOFFICE_API_GEM_TEST_PASSWORD }}
          ONLYOFFICE_API_GEM_MAIL_NAME: ${{ secrets.ONLYOFFICE_API_GEM_MAIL_NAME }}
          ONLYOFFICE_API_GEM_MAIL_PASS: ${{ secrets.ONLYOFFICE_API_GEM_MAIL_PASS }}
        run: |
          bundle exec rake
      - name: Run codecov on latest ruby
        if: matrix.ruby == '3.3'
        uses: codecov/codecov-action@v5
        with:
          token: ${{ secrets.CODECOV_TOKEN }}
          slug: ONLYOFFICE-QA/onlyoffice_api_gem
          fail_ci_if_error: true
